import { useState } from 'react'
const exemplos = [
  { area:'Compras', titulo:'Material necessário para a produção', sinal:'O fornecedor ainda não confirmou a entrega.', passos:['Comprador registra a previsão e a próxima cobrança.', 'Chefe avalia alternativa e prioriza o material crítico.', 'Recebimento confirma quantidade; comprador anexa a evidência.'], leitura:'Acompanhe dependências e prazo. Uma compra aberta não significa que o comprador está executando o tempo inteiro.' },
  { area:'Fiscal', titulo:'Nota fiscal com divergência', sinal:'A nota chegou, mas o pedido tem valor diferente.', passos:['Fiscal registra a divergência e vincula a evidência.', 'Compras confirma a condição negociada e responde à pendência.', 'Fiscal confere a correção e conclui o lançamento.'], leitura:'Registre o motivo do bloqueio e quem precisa responder. O atraso deve aparecer como problema do fluxo, não apenas como cobrança individual.' },
  { area:'PCP', titulo:'Programação do próximo turno', sinal:'Falta confirmar estoque ou disponibilidade da linha.', passos:['PCP registra a dependência com previsão de retorno.', 'Líder confirma a capacidade e sinaliza restrições.', 'PCP ajusta o plano, solicita validação e registra a versão final.'], leitura:'Use a fila de decisões para aprovar o plano. Se houver mudança depois da conclusão, reabra com justificativa.' }
]
export default function ExemplosOperacionais() {
  const [indice,setIndice]=useState(0);const e=exemplos[indice]
  return <section className="op-card op-examples"><div className="op-section-heading"><div><p className="op-eyebrow">COMO USAR NO DIA A DIA</p><h2>Do problema à próxima ação</h2></div><span className="op-demo-label">Exemplos ilustrativos · não são dados da empresa</span></div><div className="op-example-tabs" aria-label="Selecionar exemplo">{exemplos.map((ex,i)=><button key={ex.area} aria-pressed={indice===i} onClick={()=>setIndice(i)}>{ex.area}</button>)}</div><h3>{e.titulo}</h3><p>{e.sinal}</p><ol className="op-example-steps">{e.passos.map((passo,i)=><li key={passo}><b>{String(i+1).padStart(2,'0')}</b><span>{passo}</span></li>)}</ol><p className="op-example-lesson">{e.leitura}</p></section>
}
