import { useState } from 'react'
import { GraficoEtapas } from './GraficosOperacionais'
const cenarios = [
 {id:'compras',setor:'Compras',operacao:'Comprar embalagens',titulo:'Reposição de etiquetas para a produção',contexto:'O almoxarifado sinalizou estoque para dois dias. A produção precisa de 12 rolos e o fornecedor ainda não confirmou a entrega.',passos:[['ABERTA','Conferir a necessidade','Confirme especificação, saldo e data necessária com o solicitante.'],['EM_EXECUCAO','Registrar a cotação','Compare condições e documente a justificativa da escolha.'],['AGUARDANDO_APROVACAO','Solicitar aprovação','Envie a proposta para a pessoa responsável pela alçada.'],['AGUARDANDO_TERCEIRO','Cobrar confirmação','Registre retorno do fornecedor, previsão e próxima cobrança.'],['CONCLUIDA','Confirmar o recebimento','Anexe a conferência das 12 unidades e encerre a atividade.']]},
 {id:'fiscal',setor:'Fiscal',operacao:'Conferir nota fiscal',titulo:'Nota com preço diferente do pedido',contexto:'O material foi recebido, mas o valor unitário da nota diverge da condição negociada. O lançamento depende do retorno de Compras.',passos:[['ABERTA','Comparar documentos','Confira nota, pedido e recebimento.'],['BLOQUEADA','Registrar divergência','Anexe os valores divergentes; atribua a próxima ação a Compras.'],['AGUARDANDO_INFORMACAO','Acompanhar retorno','Registre previsão de resposta e informação necessária.'],['EM_EXECUCAO','Conferir correção','Valide os documentos corrigidos com o responsável competente.'],['CONCLUIDA','Registrar lançamento','Anexe a evidência da conferência e a referência do lançamento.']]},
 {id:'pcp',setor:'PCP',operacao:'Programar próximo turno',titulo:'Plano do turno com restrição de capacidade',contexto:'Um pedido prioritário entrou após o plano inicial. A equipe precisa confirmar matéria-prima, embalagens e capacidade antes de alterar a sequência.',passos:[['ABERTA','Revisar a prioridade','Confirme prazo e impacto da mudança.'],['AGUARDANDO_INFORMACAO','Confirmar recursos','Solicite estoque e capacidade disponíveis aos responsáveis.'],['EM_EXECUCAO','Ajustar programação','Registre sequência proposta e restrições.'],['AGUARDANDO_APROVACAO','Validar o plano','Solicite decisão da liderança e preserve a versão anterior.'],['CONCLUIDA','Comunicar a versão final','Distribua o plano validado e registre a passagem de turno.']]}
]
export default function SimulacoesOperacionais() {
 const [id,setId]=useState('compras'); const [passo,setPasso]=useState(0)
 const c=cenarios.find(c=>c.id===id)!; const atual=c.passos[passo]
 return <div><div className="op-training-banner"><strong>Ambiente de simulação.</strong> Cenários fictícios e realistas. Nenhuma ação nesta tela grava no banco ou altera os indicadores da empresa.</div><div className="op-filter-strip"><label>Setor e operação da simulação<select value={id} onChange={e=>{setId(e.target.value);setPasso(0)}}>{cenarios.map(c=><option key={c.id} value={c.id}>{c.setor} — {c.operacao}</option>)}</select></label><button onClick={()=>setPasso(0)}>Reiniciar simulação</button></div><div className="op-grid"><section className="op-card"><p className="op-eyebrow">{c.setor} / {c.operacao}</p><h2>{c.titulo}</h2><p>{c.contexto}</p><ol className="op-simulation-steps">{c.passos.map(([status,titulo,descricao],i)=><li key={status} data-done={i<passo} aria-current={i===passo?'step':undefined}><strong>{i<passo?'✓':`${i+1}.`} {titulo}{i===passo?' · Agora':''}</strong>{i===passo && <span>{descricao}</span>}</li>)}</ol>{passo<c.passos.length-1 ? <button onClick={()=>setPasso(p=>p+1)}>Simular etapa concluída →</button> : <p role="status">Simulação concluída. A evidência e o resultado encerram o fluxo.</p>}</section><div><GraficoEtapas dados={atual[0]==='CONCLUIDA'?[]:[{nome:atual[0],valor:1}]}/><section className="op-card"><h2>Leitura da situação</h2><p role="status">Etapa simulada: <strong>{atual[0].toLowerCase().replaceAll('_',' ')}</strong>.</p><p>{atual[2]}</p><p className="op-caption">Na operação real, as respostas de conferência e aprovação continuam exclusivas das pessoas indicadas.</p></section></div></div></div>
}
